# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-16 16:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vehicles_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cars', 'CARS'), ('motorbikes', 'MOTORBIKES'), ('trucks', 'TRUCKS')], default='cars', max_length=100)),
                ('full_name', models.CharField(default=None, max_length=250)),
                ('phone', models.CharField(default=None, max_length=20)),
                ('search_counter', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=250)),
                ('city', models.CharField(choices=[('islamabad', 'ISLAMABAD'), ('karachi', 'KARACHI'), ('lahore', 'LAHORE'), ('peshawar', 'PESHAWAR'), ('quetta', 'QUETTA'), ('multan', 'MULTAN'), ('faisalabad', 'FAISALABAD')], default='islamabad', max_length=100)),
                ('price', models.PositiveIntegerField(default=10)),
                ('brand', models.CharField(choices=[('audi', 'AUDI'), ('bmw', 'BMW'), ('mercedes', 'MERCEDES'), ('suzuki', 'SUZUKI'), ('toyota', 'TOYOTA'), ('lexus', 'LEXUS'), ('nissan', 'NISSAN'), ('honda', 'HONDA'), ('hyundai', 'HYUNDAI'), ('jeep', 'JEEP'), ('mazda', 'MAZDA'), ('mitsubishi', 'MITSUBISHI'), ('daewoo', 'DAEWOO')], default='honda', max_length=100)),
                ('modelyear', models.IntegerField(default=0)),
                ('condition', models.CharField(choices=[('new', 'NEW'), ('used', 'USED')], default='new', max_length=100)),
                ('mileage', models.IntegerField(default=0)),
                ('details', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('air_conditioner', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=100)),
                ('power_windows', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=100)),
                ('power_steering', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=100)),
                ('automatic_break_system', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=100)),
                ('air_bags', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=100)),
                ('cd_player', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=100)),
                ('image', models.FileField(blank=True, db_index=True, upload_to=vehicles_app.models.get_image_filename, verbose_name='Image')),
                ('image1', models.FileField(blank=True, db_index=True, null=True, upload_to=vehicles_app.models.get_image_filename)),
                ('image2', models.FileField(blank=True, db_index=True, null=True, upload_to=vehicles_app.models.get_image_filename)),
                ('image3', models.FileField(blank=True, db_index=True, null=True, upload_to=vehicles_app.models.get_image_filename)),
                ('image4', models.FileField(blank=True, db_index=True, null=True, upload_to=vehicles_app.models.get_image_filename)),
                ('image5', models.FileField(blank=True, db_index=True, null=True, upload_to=vehicles_app.models.get_image_filename)),
                ('image6', models.FileField(blank=True, db_index=True, null=True, upload_to=vehicles_app.models.get_image_filename)),
                ('image7', models.FileField(blank=True, db_index=True, null=True, upload_to=vehicles_app.models.get_image_filename)),
                ('image8', models.FileField(blank=True, db_index=True, null=True, upload_to=vehicles_app.models.get_image_filename)),
                ('image9', models.FileField(blank=True, db_index=True, null=True, upload_to=vehicles_app.models.get_image_filename)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
